Sogar registry
Devolutions/sogar pull request #5
Opened 2021-06-14 12:08 UTC by AnastasiiaRomaniuk

2021-06-14 20:59 UTC, CBenoit requested changes
Thank you! Here are a few suggestions.

2021-06-14 20:59 UTC, CBenoit commented on rust/sogar/sogar-core/src/sogar_registry.rs
> +pub struct SogarController;
Nothing prevents us from building a SogarController without calling `SogarController::new` here.
You can add a zero-sized attribute so we need to call `new` and checks are performed.
```suggestion
pub struct SogarController { _priv: () }
```

2021-06-15 10:12 UTC, AnastasiiaRomaniuk commented on rust/sogar/sogar-core/src/sogar_config.rs
>      let mut mime_mapping = HashMap::with_capacity(32);
done

2021-06-15 10:12 UTC, AnastasiiaRomaniuk commented on rust/sogar/sogar-core/src/sogar_registry.rs
> +pub struct SogarController;
done

2021-06-15 10:12 UTC, AnastasiiaRomaniuk commented on rust/sogar/sogar-core/src/lib.rs
> +pub mod sogar_registry;
done

2021-06-15 15:33 UTC, CBenoit approved these changes
LGTM. I'll merge after testing.

2021-06-17 16:24 UTC, merged