Fixed content.yaml file, array is named artifacts + add info in logs
Devolutions/sogar pull request #6
Opened 2021-07-09 18:54 UTC by fdubois1

1 - I fixed the content.yaml file content

The content.yaml file was something like this : 
```
blobs: 
  84190ded607550bc7dc39f435b82a02722ccb2a21ac6d0dbd3a9e1f730eae559: video/webm
  d38bc9c7-fa34-4575-9c13-fa8720954ef8: application/vnd.oci.image.manifest.v1+json
```

and it was deserialized in that struct
```
#[derive(Deserialize)]
struct ArtifactsData {
    artifacts: HashMap<String, String>,
}
```
It failed. I fixed that.

2 - I added a trace if you try to read a content file that doesn't exist.
3 - I bumped the version to 0.1.1

2021-07-09 19:28 UTC, CBenoit commented on rust/sogar/sogar-core/src/registry.rs
> +                artifacts: HashMap<String, String>,
I think it was supposed to be `blobs` here and not `artifacts`

2021-07-09 19:37 UTC, CBenoit requested changes
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#definitions

This may be useful to understand the terminology here.

My understanding is that we have a *single artifact* composed of *multiple blobs*

2021-07-09 20:05 UTC, fdubois1 commented on rust/sogar/sogar-core/src/registry.rs
> +                artifacts: HashMap<String, String>,
We could change artifacts here by blobs or change blobs by artifact. Both will work as long as it is coherent. I asked Anastasiia, that content.yaml file doesn't follow any spec and I could change blobs by artifacts.

And we write that file in a function called `add_artifacts_info`, it sounds artifacts. But I think there is also the blob type so at the end, both would work I think.

2021-07-12 07:14 UTC, AnastasiiaRomaniuk commented on rust/sogar/sogar-core/src/registry.rs
> +                artifacts: HashMap<String, String>,
The content.yaml file contains map that consist of blob or manifest as key and the content type as value, so I think artifacts will be more accurate name.

2021-07-12 13:36 UTC, CBenoit approved these changes

2021-07-12 14:10 UTC, AnastasiiaRomaniuk approved these changes

2021-07-12 14:56 UTC, merged